### ISSUE TITLE
When allocating HMA the requested size is not rounded up to paragraph

### ISSUE THREAD

**Issue by andrewbird** [FDOS/kernel#101]
When using int2f/0x4a02 to get an HMA block the requested size is not rounded up with respect to paragraph, as it is on MS-DOS 6.22/7.0/7.1.  This was recently fixed in FDPP https://github.com/dosemu2/fdpp/commit/e7fe81d458f7f68f9c331a22c788895cfd341156
See https://github.com/dosemu2/dosemu2/blob/7454efb873977214cd8605380954a4cc86a53441/test/func_memory_hma.py#L61 for an example test, where the requested size is 35 bytes, and the expectation is 48 bytes.

**Comment by ecm-pushbx** [comment]
This patch as is will overflow for `bx` > 0FFF0h.

**Comment by andrewbird** [comment]
Well spotted.

**Comment by PerditionC** [comment]
updating the hma allocation functions are on my todo list along making sure that the kernel handles multiple umb providers.  I am reworking some initialization code, which I plan to include memory management as part of, along with the gpt support I'm working on

**Comment by andrewbird** [comment]
> updating the hma allocation functions are on my todo list

Will you support the Win9x HMA layout too, see http://www.ctyme.com/intr/rb-4818.htm?

**Comment by andrewbird** [comment]
Cool, then the means the mcbs command in dosdebug can display it nicely.
