### ISSUE TITLE
Systems without BIOS drivers for USB keyboards cannot have FreeDOS installed on because it is impossible to get through the installer

### ISSUE THREAD

**Issue by AverseABFun** [FDOS/kernel#111]
And it is unnecessary to create drivers, as Bret Johnson has them at [bretjohnson.us](https://www.bretjohnson.us/).

**Comment by ecm-pushbx** [comment]
I think Bret's programs are not free software.

**Comment by AverseABFun** [comment]
> Hello @AverseABFun, hello @ecm-pushbx,
> 
> In addition, I believe Bret Johnson's drivers do not quite support newer XHCI controllers yet?
> 
> Plus I am not sure which particular PC models this may help. The PCs I have encountered that can boot in either BIOS or UEFI mode, seem to have support for USB keyboards (using some internal voodoo that makes them pretend to be PS/2 keyboards). But maybe I am wrong.
> 
> Thank you!

You're right, of course. But I got a old computer that doesn't have UEFI or built-in USB keyboard drivers.

**Comment by AverseABFun** [comment]
> I think Bret's programs are not free software.

I believe that the source is available on the website, no?

**Comment by ecm-pushbx** [comment]
> > I think Bret's programs are not free software.
> 
> I believe that the source is available on the website, no?

Free software is about more than the source being available. It means recipients have the freedoms to use, modify, and redistribute the software, for any purpose and without restrictions. This includes selling the software (possibly including the sources if there is copyleft), which this software explicitly forbids (quoth USBINTRO.DOC):

     You also
     cannot distribute the programs, documentation, or source code and charge
     (even indirectly) for their distribution.  You can charge someone enough
     to cover your actual, direct costs for distribution (disks, shipping
     materials, postage, etc.), but cannot charge for "handling".  This also
     means that you cannot distribute the programs, documentation, or source
     code directly from a web site that charges a "registration fee" in an
     attempt to make a profit or to recover direct or indirect costs for
     maintaining the web site.

**Comment by AverseABFun** [comment]
Oh, I haven't looked at the license and I probably should have before
mentioning that XD
