### ISSUE TITLE
Startup CPU check does not accept NEC V20/V30 as 186-class processors

### ISSUE THREAD

**Issue by ecm-pushbx** [FDOS/kernel#123]
The check is in https://github.com/FDOS/kernel/blob/db71b1a78337e96a89b4343b8303c6b8c4e6bb14/kernel/cpu.asm#L51-L56

A user reported in https://www.bttr-software.de/forum/forum_entry.php?id=21210 that it doesn't work on a NEC V20.

My implementation of a CPU check is either in https://hg.pushbx.org/ecm/ldebug/file/7f3440d5824d/source/init.asm#l3071 or in https://hg.pushbx.org/ecm/cpulevel/file/43b74982baeb/cpulevel.asm#l53

**Comment by PerditionC** [comment]
thank you for adding the bug report and link to code to fix.  hopefully I will have time this evening to update the check.

**Comment by ecm-pushbx** [comment]
I just tested my patched cpulevel utility (link in initial report) on the HP 95LX and its NEC V20/V30 detection does work as expected.

**Comment by ecm-pushbx** [comment]
I tested the lDebug init CPU detection much earlier when I adapted the debugger to run on the HP 95LX. It also detects the machine (`M?` command) as an 186.

**Comment by PerditionC** [comment]
draft pull request #126 with fix, need to test and verify I did test correctly.

**Comment by PerditionC** [comment]
should now treat NEC V20/V30 as 186 and work on 186 compiled kernels
