### ISSUE TITLE
Russian codepage

### ISSUE THREAD

**Issue by petr-akhlamov** [FDOS/kernel#17]
Now in russian version of FreeDOS incorrect displayed russian symbols due missing needed configuration. Can you please add to Freedos for russian version to autoexec.bat content of command setfont.bat from https://github.com/shidel/FDI/blob/master/LANGUAGE/RU/SETFONT.BAT
![VirtualBox_freedos_10_01_2020_12_02_23](https://user-images.githubusercontent.com/16255202/72140298-80b02480-33a1-11ea-80d1-c81779450c01.png)

**Comment by andrewbird** [comment]
@PerditionC can this be closed or moved, it isn't relevant to the kernel?

**Comment by cardpuncher** [comment]
I did a FreeDOS 1.3 install in Russian on VirtualBox and asked a Russian friend if on the following screenshot everything was correct.
![Screenshot at 2023-01-27 20-53-52](https://user-images.githubusercontent.com/64688741/215771051-12b2ff68-ee6b-49e7-acfa-58e64d540c72.gif)

According to her, everything is alright. So this report can probably be closed.

**Comment by petr-akhlamov** [comment]
Yes. In last release problems with russian codepage are missing.
