### ISSUE TITLE
Upstream fork

### ISSUE THREAD

**Issue by andrewbird** [FDOS/kernel#33]
Hi @PerditionC I hope you don't think this is impertinent, but I'm thinking that it's probably time to ask https://support.github.com/contact?tags=rr-forks about making this project a stand-alone (in Github view) project rather than a child fork of https://github.com/PerditionC/fdkernel. I'm sure then it will become obvious to potential contributors which one is the primary fork to submit patches and issues to. I'm not sure if they can make the perditionc one a child of fdos, which I suppose would be ideal. I don't expect they will have any problem with your request as you own both the personal account and the FDOS team.

**Comment by PerditionC** [comment]
Done.

**Comment by andrewbird** [comment]
Thanks, that's excellent it looks even better than I'd hoped for!
On another note I'm testing out a release build/test/create workflow over at my temporary repo https://github.com/andrewbird/test-kernel-release. See the releases page I'm almost there, but I could use some input on what exactly should be in the binary release file? Currently I have only gcc / watcom kernels plus their map files.
