### ISSUE TITLE
Return sucess errors

### ISSUE THREAD

**Issue by Blockland-crpto** [FDOS/kernel#36]
Hi,
I was browsing through the source code and noticed that an error kept popping up that the error code SUCCESS was not defined

**Comment by andrewbird** [comment]
As you can see from below, the success value is defined. I suspect that whatever source code viewer you are using is not picking it up properly. The source code compiles fine as is, so I really think this is an erroneous effect you are seeing. Good to close @PerditionC?

~~~
$ git grep SUCCESS \*.h
hdr/error.h:#define SUCCESS         0       /* Function was successful      */
~~~
