### ISSUE TITLE
The github blurb says "released under the GPL v2", should be "GNU GPL v2+"

### ISSUE THREAD

**Issue by ecm-pushbx** [FDOS/kernel#71]
I have two problems with that:

1. The actual license is GNU GPL v2-or-later (ie, v2+) it appears. This is a corner case that can matter. (Note that the choice depends on the exact wording in the source files' header comments.)
2. The blurb lists only "GPL" without specifying "GNU". This does not matter much but could help people unaware of what the GPL is.

**Comment by PerditionC** [comment]
You are correct, I will fix it, for some reason all these years I was thinking it didn't have the "or later" clause.  I guess I have just been reading past it or maybe it was another program I'm thinking of.  :-)

**Comment by PerditionC** [comment]
the "or later" seems to have been added
